### ISSUE TITLE
BUG#008  [Back Office] พิมพ์ใบสั่งซื้อไม่ได้

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/Autobacs-Line-OA#16]
![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/153166795/2f86beef-aec9-48ce-ad58-0654ee81eaf2)

**Comment by Sun1212312121** [comment]
![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/140136077/27286e3c-a741-47d5-a3a8-7c322359dfba)

**Comment by B95krk** [comment]
![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/153166795/46553ac4-903b-4d26-8120-df98cb633116)
