### ISSUE TITLE
BUG#027 หัวข้อแต่ละ Colum ไม่ตรงกับตาม Testcase ที่หน้า รายงานศูนย์บริการ > รายงานสรุปยอดขายประจำวัน

### ISSUE THREAD

**Issue by B95krk** [Sun1212312121/Autobacs-Line-OA#39]
![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/153166795/87132f7f-92e6-41f1-a972-6e30560d1ab1)

กรอบสีแดงคือตาม Testcase
กรอบสีเขียวคือตามหน้า POS

![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/153166795/f2a2959c-4a13-4b76-acac-a14e1fc7f27b)

**Comment by Sun1212312121** [comment]
มีการปรับแก้ไขตาม User
