### ISSUE TITLE
BUG#035 หน้าใบงานซ่อม (ใส่ข้อมูลบัตรพีทีแมกซ์) ไม่แสดงข้อมูล หมายเลขโทรศัพท์ และ รหัสบัตรบัตรประชาชน

### ISSUE THREAD

**Issue by First13422** [Sun1212312121/Autobacs-Line-OA#47]
![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/136308929/7bb8462d-4c79-4e59-9daa-58b60aba2c2a)

![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/136308929/6e314ce6-0415-4652-a693-051e26834ac7)

**Comment by Sun1212312121** [comment]
ตัดออกเนื่องจากเป็นข้อมูล PDPA ครับ
