### ISSUE TITLE
BUG001# Popup Approve โดนหน้าEdit Menu ทับ

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/Autobacs-Line-OA#57]
หมายเหตุ :  Popup Approve จะโดนทับครั้งที่ 2 เป็นทุกเมนู

https://github.com/Sun1212312121/Autobacs-Line-OA/assets/140136077/5b38fdb8-b974-4cf7-937a-cc1e858b2ef7

**Comment by saowaros123** [comment]
แสดงตาม format เดิม บน Production

![Image](https://github.com/Sun1212312121/Autobacs-Line-OA/assets/122771940/606788d2-cdfc-4236-85ed-05eead6b81c1)

**Comment by saowaros123** [comment]
ยึดตามรูปแบบเดิม
